
name: fake_profile_detector
description: Smart Fake Profile Detection System Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  mobile_scanner: ^3.5.0
  url_launcher: ^6.1.12
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_messaging: ^14.6.1
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
